// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcj9-Ce0kHdzDDP9xNFI8_VSIPagRutJ4',
    appId: '1:23657700526:web:60f7773ab08c6b1711213f',
    messagingSenderId: '23657700526',
    projectId: 'reverb-6ee9a',
    authDomain: 'reverb-6ee9a.firebaseapp.com',
    storageBucket: 'reverb-6ee9a.firebasestorage.app',
    measurementId: 'G-L1TMZY8SKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwJtjcjM6NWLPmWE1moputEuXn1pu2TnQ',
    appId: '1:23657700526:android:6e888a465825e1df11213f',
    messagingSenderId: '23657700526',
    projectId: 'reverb-6ee9a',
    storageBucket: 'reverb-6ee9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJIBEMV4ixyWpJXMWY4kSdOehV8GbW9yQ',
    appId: '1:23657700526:ios:ff54b3e636604a1e11213f',
    messagingSenderId: '23657700526',
    projectId: 'reverb-6ee9a',
    storageBucket: 'reverb-6ee9a.firebasestorage.app',
    iosBundleId: 'com.example.reverb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJIBEMV4ixyWpJXMWY4kSdOehV8GbW9yQ',
    appId: '1:23657700526:ios:ff54b3e636604a1e11213f',
    messagingSenderId: '23657700526',
    projectId: 'reverb-6ee9a',
    storageBucket: 'reverb-6ee9a.firebasestorage.app',
    iosBundleId: 'com.example.reverb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcj9-Ce0kHdzDDP9xNFI8_VSIPagRutJ4',
    appId: '1:23657700526:web:e2ac23833c0d096f11213f',
    messagingSenderId: '23657700526',
    projectId: 'reverb-6ee9a',
    authDomain: 'reverb-6ee9a.firebaseapp.com',
    storageBucket: 'reverb-6ee9a.firebasestorage.app',
    measurementId: 'G-L47M20K26K',
  );
}
